services:
  vnc-summarizer:
    image: golang:1.23
    container_name: vnc_summarizer
    restart: always
    working_dir: /app
    volumes:
      - ./src:/app
    command: sh -c "go build -o main main.go && ./main"
    networks:
      - vnc_network

networks:
  vnc_network:
    external: true
