services:
    vnc-summarizer:
        container_name: vnc_summarizer
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src/config/.env:/config/.env
        restart: always
        networks:
            - vnc_network

networks:
    vnc_network:
        external: true
